### ISSUE TITLE
Add text-shadows to theme

### ISSUE THREAD

**Issue by jes708** [priceline/design-system#348]
`x=0, y=1, blur=2 color=black` seems to be recurring.  Let's add it to theme and add support for it to be used in the Text and Heading components.

**Comment by BeniCheni** [comment]
Confirmed with @wesleymartin85 on the the text shadow style as `text-shadow: 0 1px 2px 0 rgba(0,0,0,0.5);` for normal font sizes to start with.

Potentially, @wesleymartin85 would define the large font sizes for text and the related text shadow style for in further comment.

**Comment by wesleymartin85** [comment]
@BeniCheni @dansternfeld1 here is the design documentation for text shadows [https://priceline.invisionapp.com/share/ZGRG7D6TFVP#/357099836_Headings_-_Text_Shadow](url) and a screen shot since we are open source ;) 

<img width="916" alt="Screen Shot 2019-08-15 at 12 09 29 PM" src="https://user-images.githubusercontent.com/32308814/63108767-ad2c5580-bf55-11e9-938a-ab997c7de894.png">

**Comment by James300** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add text-shadows to theme](https://trello.com/c/s3jOMiwA/46-add-text-shadows-to-theme)
